apiVersion: batch/v1
kind: CronJob
metadata:
  name: every-five
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - "curl -u \"789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP\" \"http://owdev-nginx.openwhisk:80/api/v1/namespaces/_/triggers/testbe\" -X POST -H \"Content-Type: application/json\" -d '{\"name\":\"events\"}'"
          restartPolicy: OnFailure